import type { Report } from "@/types";

export const mockReports: Report[] = [
  {
    id: "rpt-1",
    title: "January 2026 Portfolio Statement",
    category: "monthly",
    period: "Jan 2026",
    uploadedAt: "2026-02-05",
    size: "1.2 MB",
    investorId: "inv-1",
  },
  {
    id: "rpt-2",
    title: "February 2026 Portfolio Statement",
    category: "monthly",
    period: "Feb 2026",
    uploadedAt: "2026-03-05",
    size: "1.1 MB",
    investorId: "inv-1",
  },
  {
    id: "rpt-3",
    title: "Q1 2026 Performance Report",
    category: "quarterly",
    period: "Q1 2026",
    uploadedAt: "2026-04-10",
    size: "2.4 MB",
    investorId: "inv-1",
  },
  {
    id: "rpt-4",
    title: "2025 Annual Investor Report",
    category: "annual",
    period: "FY 2025",
    uploadedAt: "2026-01-20",
    size: "4.8 MB",
    investorId: "inv-1",
  },
  {
    id: "rpt-5",
    title: "Portfolio KPI Dashboard Export",
    category: "kpi",
    period: "YTD 2026",
    uploadedAt: "2026-06-01",
    size: "890 KB",
    investorId: "inv-1",
  },
  {
    id: "rpt-6",
    title: "Tax Summary 2025",
    category: "other",
    period: "2025",
    uploadedAt: "2026-02-28",
    size: "650 KB",
    investorId: "inv-1",
  },
  {
    id: "rpt-7",
    title: "Platform Consolidated Monthly",
    category: "monthly",
    period: "Jun 2026",
    uploadedAt: "2026-07-05",
    size: "3.2 MB",
  },
];
